homeassistant:
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 103
  unit_system: metric
  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo
  # Name of the location where Home Assistant is running
  name: _
  customize: !include customize.yaml

frontend:

http: 
 api_password: !secret http_password
  # Set to 1 to enable development mode
  # development: 1
 #sessions_enabled: 0
 trusted_networks:
   - 127.0.0.1
   - 192.168.1.0/24
 ip_ban_enabled: True
 login_attempts_threshold: 50

recorder:
  purge_days: 2
  db_url: !secret db_url
#  db_url: sqlite:///home/dahoiv/hass.db

logbook:

restore_states:

logger:
  default: warning
  logs:
    homeassistant.components.switch.broadlink: info
#    homeassistant.components.device_tracker: info
#    homeassistant.components.http: info
    homeassistant.components.rfxtrx: info
#    homeassistant.components.sensor.miflora: debug

history: 
  exclude:
    entities:
      - sensor.no_updates
    domains:
      - device_tracker
      - script
      - automation
      - proximity

#updater:

sun:

script: !include_dir_merge_list scripts

scene: !include scenes.yaml

automation: !include_dir_merge_list automation

light: !include lights.yaml

input_slider: !include input_slider.yaml

binary_sensor: !include binary_sensor.yaml

sensor: !include sensors.yaml

switch: !include switches.yaml

group: !include group.yaml

input_select: !include input_select.yaml

# update_ip:

proximity:
  home: 
    devices:
      - device_tracker.daniel
    tolerance: 50
    unit_of_measurement: m

notify:
  platform: pushbullet
  api_key: !secret pushbullet
  name: pushbullet

device_tracker:
- platform: nmap_tracker
  hosts: 192.168.1.1-255
  track_new_devices: no
  consider_home: 900
  interval_seconds: 10
  home_interval: 5
  scan_options: " --privileged -sP "
  # sudo setcap cap_net_raw,cap_net_admin,cap_net_bind_service+eip /usr/bin/nmap 

#- platform: luci
#  host: 192.168.1.1
#  username: root
#  password: 
#  track_new_devices: no
#  consider_home: 900
#  interval_seconds: 10

#- platform: bluetooth_tracker

- platform: gpslogger
  consider_home: 1800
  # http://:8123/api/gpslogger?api_password=XXX&latitude=%LAT&longitude=%LON&battery=%BATT&device=daniel&accuracy=%ACC

media_player:
- platform: cast
  host: 192.168.1.160

#- platform: vlc
#  name: Stue

- platform: cast
  host: 192.168.1.218

- platform: cast
  host: 192.168.1.144

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1Y0NJGR-if00-port0
  debug: False
  dummy: False

climate:
- platform: generic_thermostat
  name :  Termostat stue
  heater :  switch.ovn_stue
  target_sensor : sensor.mean_stue_temp
  target_temp : 18
  min_temp : 10
  max_temp : 25
  tolerance: 0.1

- platform: generic_thermostat
  name :  Soverom
  heater :  switch.ovn_soverom
  target_sensor : sensor.Soverom_temperature
  target_temp : 15
  min_temp : 7
  max_temp : 25
  tolerance: 0.1

#-  platform: generic_thermostat
# name :  Slow cooker
# heater :  switch.Slow_cooker
# target_sensor : sensor.temperature_rubicson_61951
# max_temp : 100

input_boolean: 
  movement3:
    initial: off
  movement_soverom:
    initial: off
  auto_heat:
    name: Auto heat
    initial: off
  steketermometer_notify_daniel:
    name: Notify Daniel
    initial: off  

sensor miflora1:
  platform: miflora
  mac: C4:7C:8D:61:7E:3B 
  name: Blomst tv
  force_update: false
  median: 3
  monitored_conditions:
   - moisture
   - light
   - temperature
   - conductivity
   - battery

sensor miflora2:
  platform: miflora
  mac: C4:7C:8D:61:7F:EC 
  name: Blomst sofa
  force_update: false
  median: 3
  monitored_conditions:
   - moisture
   - light
   - temperature
   - conductivity
   - battery

sensor miflora3:
  platform: miflora
  mac: C4:7C:8D:61:7E:5D 
  name: Blomst bokhylle
  force_update: false
  median: 3
  monitored_conditions:
   - moisture
   - light
   - temperature
   - conductivity
   - battery

#camera:
#  - platform: generic
#    still_image_url: http://raspberrypi:8082/index.html

tts:
  - platform: google
    language: 'no'

news:
 token: !secret endomondo
